image: Visual Studio 2019
version: 3.0.0.{build}
configuration: Release
platform: Any CPU
before_build:
- ps: .\SetAssemblyVersion.ps1 ${env:APPVEYOR_BUILD_VERSION}
- ps: '[System.IO.File]::ReadAllText("${env:APPVEYOR_BUILD_FOLDER}\app.config").Replace(''<add key="checkForUpdates" value="false" />'', ''<add key="checkForUpdates" value="true" />'') | Set-Content ${env:APPVEYOR_BUILD_FOLDER}\app.config'
build:
  project: EasyConnect.sln
#  verbosity: minimal
after_build:
- cmd: 7z a EasyConnect.zip %APPVEYOR_BUILD_FOLDER%\bin\%CONFIGURATION%\*.*
- cmd: copy Installer\bin\%CONFIGURATION%\EasyConnect.msi .
artifacts:
- path: EasyConnect.msi
- path: EasyConnect.zip